package comp603_project2;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ben
 */
public class COMP604_GUI_Form extends javax.swing.JFrame {

    /**
     * Creates new form COMP604_GUI_Form
     */
    public COMP604_GUI_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        label2 = new java.awt.Label();
        label7 = new java.awt.Label();
        panel5 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        label5 = new java.awt.Label();
        label8 = new java.awt.Label();
        label6 = new java.awt.Label();
        panel3 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        label44 = new java.awt.Label();
        label45 = new java.awt.Label();
        label46 = new java.awt.Label();
        label47 = new java.awt.Label();
        label48 = new java.awt.Label();
        label49 = new java.awt.Label();
        label50 = new java.awt.Label();
        label51 = new java.awt.Label();
        label52 = new java.awt.Label();
        label53 = new java.awt.Label();
        label54 = new java.awt.Label();
        label55 = new java.awt.Label();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        label56 = new java.awt.Label();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        label57 = new java.awt.Label();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        label58 = new java.awt.Label();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        label59 = new java.awt.Label();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        label60 = new java.awt.Label();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        label61 = new java.awt.Label();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        label62 = new java.awt.Label();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        label63 = new java.awt.Label();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        label64 = new java.awt.Label();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panel2 = new java.awt.Panel();
        label23 = new java.awt.Label();
        label34 = new java.awt.Label();
        label25 = new java.awt.Label();
        label26 = new java.awt.Label();
        label27 = new java.awt.Label();
        label28 = new java.awt.Label();
        label29 = new java.awt.Label();
        label30 = new java.awt.Label();
        label31 = new java.awt.Label();
        label32 = new java.awt.Label();
        label33 = new java.awt.Label();
        label42 = new java.awt.Label();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        label35 = new java.awt.Label();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        label24 = new java.awt.Label();
        jButton40 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        label36 = new java.awt.Label();
        jButton25 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        label37 = new java.awt.Label();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        label38 = new java.awt.Label();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        label39 = new java.awt.Label();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        label40 = new java.awt.Label();
        jButton74 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        label43 = new java.awt.Label();
        jButton94 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        label41 = new java.awt.Label();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        label2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("BATTLE SHIPS EXTREME!");

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setMinimumSize(new java.awt.Dimension(400, 51));
        label7.setText("BATTLE SHIPS EXTREME!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 102));
        setResizable(false);
        setSize(new java.awt.Dimension(1094, 666));
        getContentPane().setLayout(new java.awt.GridLayout());

        panel5.setLayout(new java.awt.GridBagLayout());

        panel6.setBackground(new java.awt.Color(0, 0, 102));
        panel6.setForeground(new java.awt.Color(255, 255, 255));
        panel6.setPreferredSize(new java.awt.Dimension(1200, 100));
        panel6.setLayout(new java.awt.GridLayout(1, 3));

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setMinimumSize(new java.awt.Dimension(400, 51));
        label5.setText("HOME");
        panel6.add(label5);

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        label8.setForeground(new java.awt.Color(255, 255, 255));
        label8.setMinimumSize(new java.awt.Dimension(400, 51));
        label8.setText("BATTLE SHIPS EXTREME!");
        panel6.add(label8);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setMinimumSize(new java.awt.Dimension(400, 51));
        label6.setText("AWAY");
        panel6.add(label6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel5.add(panel6, gridBagConstraints);

        panel3.setBackground(new java.awt.Color(0, 0, 102));
        panel3.setMaximumSize(new java.awt.Dimension(800, 80));
        panel3.setMinimumSize(new java.awt.Dimension(1200, 1200));
        panel3.setPreferredSize(new java.awt.Dimension(800, 500));
        panel3.setLayout(new javax.swing.BoxLayout(panel3, javax.swing.BoxLayout.LINE_AXIS));

        panel4.setBackground(new java.awt.Color(0, 0, 102));
        panel4.setPreferredSize(new java.awt.Dimension(540, 350));
        panel4.setLayout(new java.awt.GridLayout(11, 11));
        panel4.add(label44);

        label45.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label45.setForeground(new java.awt.Color(255, 255, 255));
        label45.setText(" A");
        panel4.add(label45);

        label46.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label46.setForeground(new java.awt.Color(255, 255, 255));
        label46.setText(" B");
        panel4.add(label46);

        label47.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label47.setForeground(new java.awt.Color(255, 255, 255));
        label47.setText(" C");
        panel4.add(label47);

        label48.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label48.setForeground(new java.awt.Color(255, 255, 255));
        label48.setText(" D");
        panel4.add(label48);

        label49.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label49.setForeground(new java.awt.Color(255, 255, 255));
        label49.setText(" E");
        panel4.add(label49);

        label50.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label50.setForeground(new java.awt.Color(255, 255, 255));
        label50.setText(" F");
        panel4.add(label50);

        label51.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label51.setForeground(new java.awt.Color(255, 255, 255));
        label51.setText(" G");
        panel4.add(label51);

        label52.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label52.setForeground(new java.awt.Color(255, 255, 255));
        label52.setText(" H");
        panel4.add(label52);

        label53.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label53.setForeground(new java.awt.Color(255, 255, 255));
        label53.setText("  I");
        panel4.add(label53);

        label54.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label54.setForeground(new java.awt.Color(255, 255, 255));
        label54.setText(" J");
        panel4.add(label54);

        label55.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label55.setForeground(new java.awt.Color(255, 255, 255));
        label55.setText("01");
        panel4.add(label55);

        jButton104.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton104.setText("~");
        panel4.add(jButton104);

        jButton105.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton105.setText("~");
        panel4.add(jButton105);

        jButton106.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton106.setText("~");
        panel4.add(jButton106);

        jButton107.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton107.setText("~");
        panel4.add(jButton107);

        jButton108.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton108.setText("~");
        panel4.add(jButton108);

        jButton109.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton109.setText("~");
        panel4.add(jButton109);

        jButton110.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton110.setText("~");
        panel4.add(jButton110);

        jButton111.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton111.setText("~");
        panel4.add(jButton111);

        jButton112.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton112.setText("~");
        panel4.add(jButton112);

        jButton113.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton113.setText("~");
        panel4.add(jButton113);

        label56.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label56.setForeground(new java.awt.Color(255, 255, 255));
        label56.setText("02");
        panel4.add(label56);

        jButton114.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton114.setText("~");
        panel4.add(jButton114);

        jButton115.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton115.setText("~");
        panel4.add(jButton115);

        jButton116.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton116.setText("~");
        panel4.add(jButton116);

        jButton117.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton117.setText("~");
        panel4.add(jButton117);

        jButton118.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton118.setText("~");
        panel4.add(jButton118);

        jButton119.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton119.setText("~");
        panel4.add(jButton119);

        jButton120.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton120.setText("~");
        panel4.add(jButton120);

        jButton121.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton121.setText("~");
        panel4.add(jButton121);

        jButton122.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton122.setText("~");
        panel4.add(jButton122);

        jButton123.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton123.setText("~");
        panel4.add(jButton123);

        label57.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label57.setForeground(new java.awt.Color(255, 255, 255));
        label57.setText("03");
        panel4.add(label57);

        jButton124.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton124.setText("~");
        panel4.add(jButton124);

        jButton125.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton125.setText("~");
        panel4.add(jButton125);

        jButton126.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton126.setText("~");
        panel4.add(jButton126);

        jButton127.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton127.setText("~");
        panel4.add(jButton127);

        jButton128.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton128.setText("~");
        panel4.add(jButton128);

        jButton129.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton129.setText("~");
        panel4.add(jButton129);

        jButton130.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton130.setText("~");
        panel4.add(jButton130);

        jButton131.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton131.setText("~");
        panel4.add(jButton131);

        jButton132.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton132.setText("~");
        panel4.add(jButton132);

        jButton133.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton133.setText("~");
        panel4.add(jButton133);

        label58.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label58.setForeground(new java.awt.Color(255, 255, 255));
        label58.setText("04");
        panel4.add(label58);

        jButton134.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton134.setText("~");
        panel4.add(jButton134);

        jButton135.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton135.setText("~");
        panel4.add(jButton135);

        jButton136.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton136.setText("~");
        panel4.add(jButton136);

        jButton137.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton137.setText("~");
        panel4.add(jButton137);

        jButton138.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton138.setText("~");
        panel4.add(jButton138);

        jButton139.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton139.setText("~");
        panel4.add(jButton139);

        jButton140.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton140.setText("~");
        panel4.add(jButton140);

        jButton141.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton141.setText("~");
        panel4.add(jButton141);

        jButton142.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton142.setText("~");
        panel4.add(jButton142);

        jButton143.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton143.setText("~");
        panel4.add(jButton143);

        label59.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label59.setForeground(new java.awt.Color(255, 255, 255));
        label59.setText("05");
        panel4.add(label59);

        jButton144.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton144.setText("~");
        panel4.add(jButton144);

        jButton145.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton145.setText("~");
        panel4.add(jButton145);

        jButton146.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton146.setText("~");
        panel4.add(jButton146);

        jButton147.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton147.setText("~");
        panel4.add(jButton147);

        jButton148.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton148.setText("~");
        panel4.add(jButton148);

        jButton149.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton149.setText("~");
        panel4.add(jButton149);

        jButton150.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton150.setText("~");
        panel4.add(jButton150);

        jButton151.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton151.setText("~");
        panel4.add(jButton151);

        jButton152.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton152.setText("~");
        panel4.add(jButton152);

        jButton153.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton153.setText("~");
        panel4.add(jButton153);

        label60.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label60.setForeground(new java.awt.Color(255, 255, 255));
        label60.setText("06");
        panel4.add(label60);

        jButton154.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton154.setText("~");
        panel4.add(jButton154);

        jButton155.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton155.setText("~");
        panel4.add(jButton155);

        jButton156.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton156.setText("~");
        panel4.add(jButton156);

        jButton157.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton157.setText("~");
        panel4.add(jButton157);

        jButton158.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton158.setText("~");
        panel4.add(jButton158);

        jButton159.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton159.setText("~");
        panel4.add(jButton159);

        jButton160.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton160.setText("~");
        panel4.add(jButton160);

        jButton161.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton161.setText("~");
        panel4.add(jButton161);

        jButton162.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton162.setText("~");
        panel4.add(jButton162);

        jButton163.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton163.setText("~");
        panel4.add(jButton163);

        label61.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label61.setForeground(new java.awt.Color(255, 255, 255));
        label61.setText("07");
        panel4.add(label61);

        jButton164.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton164.setText("~");
        panel4.add(jButton164);

        jButton165.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton165.setText("~");
        panel4.add(jButton165);

        jButton166.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton166.setText("~");
        panel4.add(jButton166);

        jButton167.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton167.setText("~");
        panel4.add(jButton167);

        jButton168.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton168.setText("~");
        panel4.add(jButton168);

        jButton169.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton169.setText("~");
        panel4.add(jButton169);

        jButton170.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton170.setText("~");
        panel4.add(jButton170);

        jButton171.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton171.setText("~");
        panel4.add(jButton171);

        jButton172.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton172.setText("~");
        panel4.add(jButton172);

        jButton173.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton173.setText("~");
        panel4.add(jButton173);

        label62.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label62.setForeground(new java.awt.Color(255, 255, 255));
        label62.setText("08");
        panel4.add(label62);

        jButton174.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton174.setText("~");
        panel4.add(jButton174);

        jButton175.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton175.setText("~");
        panel4.add(jButton175);

        jButton176.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton176.setText("~");
        panel4.add(jButton176);

        jButton177.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton177.setText("~");
        panel4.add(jButton177);

        jButton178.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton178.setText("~");
        panel4.add(jButton178);

        jButton179.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton179.setText("~");
        panel4.add(jButton179);

        jButton180.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton180.setText("~");
        panel4.add(jButton180);

        jButton181.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton181.setText("~");
        panel4.add(jButton181);

        jButton182.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton182.setText("~");
        panel4.add(jButton182);

        jButton183.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton183.setText("~");
        panel4.add(jButton183);

        label63.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label63.setForeground(new java.awt.Color(255, 255, 255));
        label63.setText("09");
        panel4.add(label63);

        jButton184.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton184.setText("~");
        panel4.add(jButton184);

        jButton185.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton185.setText("~");
        panel4.add(jButton185);

        jButton186.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton186.setText("~");
        panel4.add(jButton186);

        jButton187.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton187.setText("~");
        panel4.add(jButton187);

        jButton188.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton188.setText("~");
        panel4.add(jButton188);

        jButton189.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton189.setText("~");
        panel4.add(jButton189);

        jButton190.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton190.setText("~");
        panel4.add(jButton190);

        jButton191.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton191.setText("~");
        panel4.add(jButton191);

        jButton192.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton192.setText("~");
        panel4.add(jButton192);

        jButton193.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton193.setText("~");
        panel4.add(jButton193);

        label64.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label64.setForeground(new java.awt.Color(255, 255, 255));
        label64.setText("10");
        panel4.add(label64);

        jButton194.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton194.setText("~");
        panel4.add(jButton194);

        jButton195.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton195.setText("~");
        panel4.add(jButton195);

        jButton196.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton196.setText("~");
        panel4.add(jButton196);

        jButton197.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton197.setText("~");
        panel4.add(jButton197);

        jButton198.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton198.setText("~");
        panel4.add(jButton198);

        jButton199.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton199.setText("~");
        panel4.add(jButton199);

        jButton200.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton200.setText("~");
        panel4.add(jButton200);

        jButton201.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton201.setText("~");
        panel4.add(jButton201);

        jButton202.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton202.setText("~");
        panel4.add(jButton202);

        jButton203.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton203.setText("~");
        panel4.add(jButton203);

        panel3.add(panel4);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        panel3.add(jSeparator1);

        panel2.setBackground(new java.awt.Color(0, 0, 102));
        panel2.setPreferredSize(new java.awt.Dimension(540, 350));
        panel2.setLayout(new java.awt.GridLayout(11, 11));
        panel2.add(label23);

        label34.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label34.setForeground(new java.awt.Color(255, 255, 255));
        label34.setText(" A");
        panel2.add(label34);

        label25.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label25.setForeground(new java.awt.Color(255, 255, 255));
        label25.setText(" B");
        panel2.add(label25);

        label26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label26.setForeground(new java.awt.Color(255, 255, 255));
        label26.setText(" C");
        panel2.add(label26);

        label27.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label27.setForeground(new java.awt.Color(255, 255, 255));
        label27.setText(" D");
        panel2.add(label27);

        label28.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label28.setForeground(new java.awt.Color(255, 255, 255));
        label28.setText(" E");
        panel2.add(label28);

        label29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label29.setForeground(new java.awt.Color(255, 255, 255));
        label29.setText(" F");
        panel2.add(label29);

        label30.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label30.setForeground(new java.awt.Color(255, 255, 255));
        label30.setText(" G");
        panel2.add(label30);

        label31.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label31.setForeground(new java.awt.Color(255, 255, 255));
        label31.setText(" H");
        panel2.add(label31);

        label32.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label32.setForeground(new java.awt.Color(255, 255, 255));
        label32.setText("  I");
        panel2.add(label32);

        label33.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label33.setForeground(new java.awt.Color(255, 255, 255));
        label33.setText(" J");
        panel2.add(label33);

        label42.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label42.setForeground(new java.awt.Color(255, 255, 255));
        label42.setText("01");
        panel2.add(label42);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setText("~");
        panel2.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setText("~");
        panel2.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setText("~");
        panel2.add(jButton6);

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton11.setText("~");
        panel2.add(jButton11);

        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton12.setText("~");
        panel2.add(jButton12);

        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton13.setText("~");
        panel2.add(jButton13);

        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton14.setText("~");
        panel2.add(jButton14);

        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton15.setText("~");
        panel2.add(jButton15);

        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton16.setText("~");
        panel2.add(jButton16);

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setText("~");
        panel2.add(jButton10);

        label35.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label35.setForeground(new java.awt.Color(255, 255, 255));
        label35.setText("02");
        panel2.add(label35);

        jButton27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton27.setText("~");
        panel2.add(jButton27);

        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton28.setText("~");
        panel2.add(jButton28);

        jButton29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton29.setText("~");
        panel2.add(jButton29);

        jButton30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton30.setText("~");
        panel2.add(jButton30);

        jButton31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton31.setText("~");
        panel2.add(jButton31);

        jButton32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton32.setText("~");
        panel2.add(jButton32);

        jButton33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton33.setText("~");
        panel2.add(jButton33);

        jButton34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton34.setText("~");
        panel2.add(jButton34);

        jButton26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton26.setText("~");
        panel2.add(jButton26);

        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton24.setText("~");
        panel2.add(jButton24);

        label24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label24.setForeground(new java.awt.Color(255, 255, 255));
        label24.setText("03");
        panel2.add(label24);

        jButton40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton40.setText("~");
        panel2.add(jButton40);

        jButton38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton38.setText("~");
        panel2.add(jButton38);

        jButton39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton39.setText("~");
        panel2.add(jButton39);

        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton18.setText("~");
        panel2.add(jButton18);

        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton19.setText("~");
        panel2.add(jButton19);

        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton20.setText("~");
        panel2.add(jButton20);

        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton21.setText("~");
        panel2.add(jButton21);

        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton22.setText("~");
        panel2.add(jButton22);

        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton23.setText("~");
        panel2.add(jButton23);

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton17.setText("~");
        panel2.add(jButton17);

        label36.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label36.setForeground(new java.awt.Color(255, 255, 255));
        label36.setText("04");
        panel2.add(label36);

        jButton25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton25.setText("~");
        panel2.add(jButton25);

        jButton37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton37.setText("~");
        panel2.add(jButton37);

        jButton41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton41.setText("~");
        panel2.add(jButton41);

        jButton42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton42.setText("~");
        panel2.add(jButton42);

        jButton43.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton43.setText("~");
        panel2.add(jButton43);

        jButton44.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton44.setText("~");
        panel2.add(jButton44);

        jButton45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton45.setText("~");
        panel2.add(jButton45);

        jButton46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton46.setText("~");
        panel2.add(jButton46);

        jButton47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton47.setText("~");
        panel2.add(jButton47);

        jButton48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton48.setText("~");
        panel2.add(jButton48);

        label37.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label37.setForeground(new java.awt.Color(255, 255, 255));
        label37.setText("05");
        panel2.add(label37);

        jButton49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton49.setText("~");
        panel2.add(jButton49);

        jButton50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton50.setText("~");
        panel2.add(jButton50);

        jButton51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton51.setText("~");
        panel2.add(jButton51);

        jButton52.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton52.setText("~");
        panel2.add(jButton52);

        jButton53.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton53.setText("~");
        panel2.add(jButton53);

        jButton54.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton54.setText("~");
        panel2.add(jButton54);

        jButton55.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton55.setText("~");
        panel2.add(jButton55);

        jButton56.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton56.setText("~");
        panel2.add(jButton56);

        jButton57.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton57.setText("~");
        panel2.add(jButton57);

        jButton58.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton58.setText("~");
        panel2.add(jButton58);

        label38.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label38.setForeground(new java.awt.Color(255, 255, 255));
        label38.setText("06");
        panel2.add(label38);

        jButton61.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton61.setText("~");
        panel2.add(jButton61);

        jButton62.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton62.setText("~");
        panel2.add(jButton62);

        jButton63.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton63.setText("~");
        panel2.add(jButton63);

        jButton64.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton64.setText("~");
        panel2.add(jButton64);

        jButton65.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton65.setText("~");
        panel2.add(jButton65);

        jButton66.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton66.setText("~");
        panel2.add(jButton66);

        jButton67.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton67.setText("~");
        panel2.add(jButton67);

        jButton68.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton68.setText("~");
        panel2.add(jButton68);

        jButton69.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton69.setText("~");
        panel2.add(jButton69);

        jButton70.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton70.setText("~");
        panel2.add(jButton70);

        label39.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label39.setForeground(new java.awt.Color(255, 255, 255));
        label39.setText("07");
        panel2.add(label39);

        jButton71.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton71.setText("~");
        panel2.add(jButton71);

        jButton72.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton72.setText("~");
        panel2.add(jButton72);

        jButton73.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton73.setText("~");
        panel2.add(jButton73);

        jButton75.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton75.setText("~");
        panel2.add(jButton75);

        jButton76.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton76.setText("~");
        panel2.add(jButton76);

        jButton77.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton77.setText("~");
        panel2.add(jButton77);

        jButton78.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton78.setText("~");
        panel2.add(jButton78);

        jButton79.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton79.setText("~");
        panel2.add(jButton79);

        jButton80.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton80.setText("~");
        panel2.add(jButton80);

        jButton60.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton60.setText("~");
        panel2.add(jButton60);

        label40.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label40.setForeground(new java.awt.Color(255, 255, 255));
        label40.setText("08");
        panel2.add(label40);

        jButton74.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton74.setText("~");
        panel2.add(jButton74);

        jButton84.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton84.setText("~");
        panel2.add(jButton84);

        jButton85.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton85.setText("~");
        panel2.add(jButton85);

        jButton86.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton86.setText("~");
        panel2.add(jButton86);

        jButton87.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton87.setText("~");
        panel2.add(jButton87);

        jButton88.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton88.setText("~");
        panel2.add(jButton88);

        jButton89.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton89.setText("~");
        panel2.add(jButton89);

        jButton90.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton90.setText("~");
        panel2.add(jButton90);

        jButton91.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton91.setText("~");
        panel2.add(jButton91);

        jButton92.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton92.setText("~");
        panel2.add(jButton92);

        label43.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label43.setForeground(new java.awt.Color(255, 255, 255));
        label43.setText("09");
        panel2.add(label43);

        jButton94.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton94.setText("~");
        panel2.add(jButton94);

        jButton95.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton95.setText("~");
        panel2.add(jButton95);

        jButton96.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton96.setText("~");
        panel2.add(jButton96);

        jButton97.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton97.setText("~");
        panel2.add(jButton97);

        jButton98.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton98.setText("~");
        panel2.add(jButton98);

        jButton99.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton99.setText("~");
        panel2.add(jButton99);

        jButton100.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton100.setText("~");
        panel2.add(jButton100);

        jButton101.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton101.setText("~");
        panel2.add(jButton101);

        jButton102.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton102.setText("~");
        panel2.add(jButton102);

        jButton103.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton103.setText("~");
        panel2.add(jButton103);

        label41.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label41.setForeground(new java.awt.Color(255, 255, 255));
        label41.setText("10");
        panel2.add(label41);

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setText("~");
        panel2.add(jButton7);

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setText("~");
        panel2.add(jButton8);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setText("~");
        panel2.add(jButton9);

        jButton35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton35.setText("~");
        panel2.add(jButton35);

        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton36.setText("~");
        panel2.add(jButton36);

        jButton59.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton59.setText("~");
        panel2.add(jButton59);

        jButton81.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton81.setText("~");
        panel2.add(jButton81);

        jButton82.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton82.setText("~");
        panel2.add(jButton82);

        jButton83.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton83.setText("~");
        panel2.add(jButton83);

        jButton93.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton93.setText("~");
        panel2.add(jButton93);

        panel3.add(panel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panel5.add(panel3, gridBagConstraints);

        getContentPane().add(panel5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COMP604_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COMP604_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COMP604_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COMP604_GUI_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COMP604_GUI_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label2;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label27;
    private java.awt.Label label28;
    private java.awt.Label label29;
    private java.awt.Label label30;
    private java.awt.Label label31;
    private java.awt.Label label32;
    private java.awt.Label label33;
    private java.awt.Label label34;
    private java.awt.Label label35;
    private java.awt.Label label36;
    private java.awt.Label label37;
    private java.awt.Label label38;
    private java.awt.Label label39;
    private java.awt.Label label40;
    private java.awt.Label label41;
    private java.awt.Label label42;
    private java.awt.Label label43;
    private java.awt.Label label44;
    private java.awt.Label label45;
    private java.awt.Label label46;
    private java.awt.Label label47;
    private java.awt.Label label48;
    private java.awt.Label label49;
    private java.awt.Label label5;
    private java.awt.Label label50;
    private java.awt.Label label51;
    private java.awt.Label label52;
    private java.awt.Label label53;
    private java.awt.Label label54;
    private java.awt.Label label55;
    private java.awt.Label label56;
    private java.awt.Label label57;
    private java.awt.Label label58;
    private java.awt.Label label59;
    private java.awt.Label label6;
    private java.awt.Label label60;
    private java.awt.Label label61;
    private java.awt.Label label62;
    private java.awt.Label label63;
    private java.awt.Label label64;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    // End of variables declaration//GEN-END:variables
}
